name: Build APK FAnimes

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Aumentar Memória e Build
        env:
          # AQUI ESTÁ O PULO DO GATO: Aumentando a memória do Java/Gradle
          _JAVA_OPTIONS: "-Xmx4g"
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g"
        run: |
          flutter pub get
          flutter build apk --debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

